Razor/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GreetWithRazor.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}


Razor/Pages/Greeted.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using GreetFunction;

namespace GreetWithRazor.Pages;


public class GreetedModel : PageModel
{

  private IGreet _greetings;
  private readonly ILogger<IndexModel> _logger;

  public GreetedModel(ILogger<IndexModel> logger, IGreet GreetUsingDatabase)
  {
    _logger = logger;
    _greetings = GreetUsingDatabase;
  }
  public Dictionary<string, int> List
  {
    // get
    // {
    //   return _greetings.GetList();
    // }
    get;
    set;

  }
  public string Message
  {
    // get
    // {
    //   return _greetings.Message();
    // }
    get;
    set;
  }
  [BindProperty]
  public Greeter Greet { get; set; }

  [BindProperty]
  public string Handler { get; set; }

  public void OnGet()
  {

    List = _greetings.GetList();
    //Message = _greetings.Message();


  }
  public void OnPostRemove(string name)
  {

    _greetings.Remove(Greet.FirstName);
    Greet.FirstName = "";
    ModelState.Clear();
    List = _greetings.GetList();


  }

  public void OnPostClear(string name)
  {
    if (Handler == "clear")
    {
      _greetings.Clear();
      List = _greetings.GetList();
      Message = _greetings.Message();


    }

  }


}


Razor/Pages/GuideUser.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GreetWithRazor.Pages;

public class GuideUserModel : PageModel
{
  private readonly ILogger<GuideUserModel> _logger;

  public GuideUserModel(ILogger<GuideUserModel> logger)
  {
    _logger = logger;
  }

  [BindProperty]
  public string Action { get; set; }

  public void OnGet()
  {
  }

  public IActionResult OnPostContinue()
  {
    return Redirect("/Index");

  }
}


Razor/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MongoDB.Bson;
using MongoDB.Driver;
using GreetFunction;
using System.Text.RegularExpressions;

namespace GreetWithRazor.Pages;

public class IndexModel : PageModel
{

  private IGreet _greetings;
  private readonly ILogger<IndexModel> _logger;

  public IndexModel(ILogger<IndexModel> logger, IGreet GreetWithMongo)
  {
    _logger = logger;
    _greetings = GreetWithMongo;
  }



  public void OnGet()
  {

  }
  public string? Greeting { get; set; }
  public int count
  {
    // get
    // {
    //   return _greetings.Counter();
    // }
    get; set;
  }

  public Dictionary<string, int> List { get; set; }

  public string clear { get; set; }




  [BindProperty]
  public Greeter Greet { get; set; }
  [BindProperty]
  public string Handler { get; set; }


  public void OnPostGreet()
  {
    if (Handler == "Greet")
    {
      if (ModelState.IsValid)
      {

        _greetings.AddUsers(Greet.FirstName, 1);
        Greeting = _greetings.Greetings(Greet.FirstName, Greet.Language);
        List = _greetings.GetList();
        _greetings.Counter();
        Greet.FirstName = "";
        Greet.Language = "";
        ModelState.Clear();
      }

    }

  }
  public IActionResult OnPostGreetedPeople()
  {
    if (Handler == "greetedPeople")
    {

      List = _greetings.GetList();

    }
    return Redirect("/Greeted");


  }


}

Razor/Pages/Greeted.cshtml
@page
@model GreetWithRazor.Pages.GreetedModel
@{
  ViewData["Title"] = "Greeted page";
}
<div class="text-center">
    <h2 class="display-4">Greeted People</h2>

  <div class="table">
    @if (Model.List != null)
    {
    <table class="table table-success table-striped">
      <tr>
        <th>FirstName</th> 
        <th>Greeted Times</th>
        <th>Remove Greeted user</th>
        </tr>
    @foreach (KeyValuePair<string, int> kv in @Model.List)
    {
      <tr>
        <td>@kv.Key </td>
      
        <td>@kv.Value</td>
        <td>
          <form asp-page-handler="remove" method="post">
              <input asp-for="Greet.FirstName" type="hidden" asp-route-name="name" value="@kv.Key" />
             <button asp-page-handler="remove" asp-route-name="name" class="btn1, btn btn-danger ">Remove</button>
          </form>
        </td>
      </tr>
    }
    </table>
    }
  </div>
    
      <div class="greeted">

        @if(Model.Handler == "clear")
            {
              @Model.Message;
            }
      </div>
            <form asp-page-handler="clear" method="post">
            <button asp-page-handler="clear" class="btn1, btn btn-danger btn-lg" type="clear" >Clear All</button>
            </form>
  

</div>

Razor/Pages/GuideUser.cshtml
@page
@model GuideUserModel
@{
    ViewData["Title"] = "Welcome to the Greetings App";
}
<h1>@ViewData["Title"]</h1>
<div class="instructions">
    <h3>Instructions of the App</h3>
<p>
    <ul>
        <li>To greet people enter the name of the person and select a language</li>
        <li>Click greet to see the message at the bottom</li>
        <li>To see greeted people click the greeted button</li>
        <li>To remove someone in the list click the remove button next to the person</li>
        <li>To delete all the people you have greeted click the clear All button</li>
        <li>Click the continue button to go to the greetings page</li>
    </ul>
</p>
<form class="go" method="post">
<button asp-page-handler="continue" type="submit" class="btn btn-primary">Continue</button>
</form>

</div>

Razor/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
<div class="card"  style="background-color: #e3f2fd;">

    <h1 class="display-4">Greetings App</h1>
    
    <div class="name">
        <form method="post">

         <div class="firstname">
            @if(Model.Handler != "clear")
            {
            <div class="validation">
            <span asp-validation-for="Greet!.FirstName" class="text-danger"></span>
            </div>
            }
            <label asp-for="Greet!.FirstName">Name:</label>
            <input asp-for="Greet!.FirstName"  placeholder="First name" aria-label="First name" /><br>
        </div>
        <div class="radio">
            @if(Model.Handler != "clear")
            {
            <div class="validation">
             <span asp-validation-for="Greet!.Language" class="text-danger"></span>
            </div>

            }
        
             <div class="form-check form-check-inline">
            <input  asp-for="Greet!.Language" class="form-check-input" type="radio" id="flexchecked" value="isixhosa">
            <label class="form-check-label" for="Greet!.Language">IsiXhosa</label>
            </div>
            <div class="form-check form-check-inline">
            <input asp-for="Greet!.Language" class="form-check-input"  type="radio"  id="Language" value="setswana">
            <label class="form-check-label" for="inlineRadio2">Setswana</label>
            </div>
            <div class="form-check form-check-inline">
            <input asp-for="Greet!.Language" class="form-check-input"  type="radio"  id="Language" value="isizulu">
            <label class="form-check-label" for="inlineRadio3">IsiZulu</label>
            </div>
        </div> 
        <div class="counter">
            counter: @Model.count
        </div>
                <div class="button">
                <button asp-page-handler="Greet" class="btn btn-primary btn-lg" type="submit" >Greet</button>
                <button asp-page-handler="greetedPeople" class="btn btn-danger btn-lg" type="greetedPeople">Greeted</button>
                </div>

        </form>
    </div>


    <div class="greeting">
    @if(Model.Greet!= null && Model.Greet.FirstName != null)
    {
    @Model.Greeting
    }
    </div>
</div>
</div>





Razor/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GreetWithRazor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GreetWithRazor.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3"  style="background-color: #e3f2fd;">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">GreetWithRazor</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/GuideUser">Help</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                         @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Greeted">Greeted</a>
                        </li> *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color: #e3f2fd;">
        <div class="container">
            &copy; 2022 - GreetWithRazor - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>